### ISSUE TITLE
Can't figure out how to subtract money from a player

### ISSUE THREAD

**Issue by TheMcMurder** [nhumrich/councils-dilemna#7]
Trying to invoke: https://github.com/nhumrich/councils-dilemna/blob/master/cdilemna/user.py#L19

Here: https://github.com/nhumrich/councils-dilemna/blob/master/cdilemna/core.py#L50

Gives me an error about multiple positional arguments. I'm not really sure what the problem is do you have any suggestions @nhumrich

**Comment by nhumrich** [comment]
@TheMcMurder the issue here is that in a python class, every method has to start with an implicit `self`  argument. `self` is essentially the equivalent of `this` in javascript, except that in python, you have to explicitly list it as an argument. 
So, spend money should be
```python
 def spend_money(self, amount_to_spend):
```

**Comment by TheMcMurder** [comment]
Good to know. Thank you! 😁
